# This is a config for E2B sandbox template.
# You can use 'template_id' (fpcnw9sgiiran506prsp) or 'template_name (open-interpreter-sandbox) from this config to spawn a sandbox:

# Python SDK
# from e2b import Sandbox
# sandbox = Sandbox(template='open-interpreter-sandbox')

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create({ template: 'open-interpreter-sandbox' })

template_id = "fpcnw9sgiiran506prsp"
dockerfile = "e2b.Dockerfile"
template_name = "open-interpreter-sandbox"
start_cmd = "uvicorn server:app --host 0.0.0.0 --port 80"
