# This is a config for E2B sandbox template.
# You can use 'template_id' (biwzcvmzxhvvew5r1u5i) or 'template_name (e2b-ois-image) from this config to spawn a sandbox:

# Python SDK
# from e2b import Sandbox
# sandbox = Sandbox(template='e2b-ois-image')

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create({ template: 'e2b-ois-image' })

dockerfile = "e2b.Dockerfile"
template_name = "e2b-ois-image"
template_id = "biwzcvmzxhvvew5r1u5i"
