# This is a config for E2B sandbox template.
# You can use 'template_id' (fpcnw9sgiiran506prsp) or 'template_name (e2b-ois-image-dev) from this config to spawn a sandbox:

# Python SDK
# from e2b import Sandbox
# sandbox = Sandbox(template='e2b-ois-image-dev')

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create({ template: 'e2b-ois-image-dev' })

dockerfile = "e2b.Dockerfile"
template_name = "e2b-ois-image-dev"
template_id = "fpcnw9sgiiran506prsp"
