model_list: 
  - model_name: gpt-3.5-turbo # user-facing model alias
    litellm_params: # all params accepted by litellm.completion() - https://docs.litellm.ai/docs/completion/input
      model: openai/gpt-3.5-turbo
      #api_key: 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
  