name: Backend server

env:
  IMAGE: e2b-agentboard/backend

on:
  workflow_call:
    secrets:
      service_account_email:
        required: true
      workload_identity_provider:
        required: true
      gcp_project_id:
        required: true

jobs:
  publish:
    name: Build & push
    defaults:
        run:
            working-directory: ./backend
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Service Account
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.workload_identity_provider }}
          service_account: ${{ secrets.service_account_email }}

      - name: Configure Docker
        run: gcloud --quiet auth configure-docker us-central1-docker.pkg.dev

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push docker images
        run: docker build --platform linux/amd64 --tag "${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.E2B_GCP_PROJECT_ID }}/$(IMAGE)" --push .
