name: Build and push Code Interpreter templates

on:
  push:
    paths:
      - 'sandbox-template/**'
      - '.github/workflows/template.yml'
    branches:
      - main

permissions:
  contents: read

jobs:
  buildAndPublish:
    defaults:
      run:
        working-directory: ./sandbox-template

    name: Build and Push Images
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install E2B CLI
        run: npm install -g @e2b/cli

      - name: Build e2b
        run: e2b template build
        env:
          E2B_ACCESS_TOKEN: ${{ secrets.E2B_ACCESS_TOKEN }}
